version: '3'
services:
  api-gateway:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - task-service
      - project-service
      - notification-service
      - reporting-service

  user-service:
    image: user-service-image
    ports:
      - "3001:3001"

  task-service:
    image: task-service-image
    ports:
      - "3002:3002"

  project-service:
    image: project-service-image
    ports:
      - "3003:3003"

  notification-service:
    image: notification-service-image
    ports:
      - "3004:3004"

  reporting-service:
    image: reporting-service-image
    ports:
      - "3005:3005"
